export const notableCollections = [
  "Stratospheric Birds",
  "Venusian Animals",
  "Ants",
  "Venusian Insects",
  "Penguins",
  "Birds",
  "Livestock",
  "Physics Complex",
  "Pets",
  "Fish",
  "Immigration Shuttles",
  "Floating Habs",
  "Tardigrades",
  "Jovian Lanterns",
  "Io Mining Industries",
  "Ganymede Colony",
  "St. Joseph of Cupertino Mission",
  "Water Import From Europa",
  "Extremophiles",
  "Neptunian Power Consultants",
  "Asteroid Deflection System",
  "Decomposers",
];